LPS-166868
adolfopa/liferay-portal pull request #1469
Opened 2022-11-25 03:24 UTC by tototrinh

Hi @adolfopa 
I have some updates:
- Change the commit message from _Edit in Google Docs_ to _Edit in Google Drive_.
- SessionError key from _GoogleDriveFileNotFound_ to _googleDriveFileWasDeleted_.

Please help me take a look and let me know whether I missed or misunderstood something.
Thanks.

2022-11-25 03:24 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-25 07:42 UTC, adolfopa requested changes

2022-11-25 07:42 UTC, adolfopa commented on modules/apps/document-library-opener/document-library-opener-google-drive-web/src/main/java/com/liferay/document/library/opener/google/drive/web/internal/DLOpenerGoogleDriveManager.java
> +					"The GoogleDrive file does not exist",
Shouldn't this be "... Google Drive ..." instead of "... GoogleDrive ... "?

2022-11-25 07:42 UTC, adolfopa commented on modules/apps/document-library-opener/document-library-opener-google-drive-web/src/main/java/com/liferay/document/library/opener/google/drive/web/internal/DLOpenerGoogleDriveManager.java
> +					"The GoogleDrive file does not exist",
"... GoogleDrive ..." -> "... Google Drive ..."

2022-11-25 07:42 UTC, adolfopa commented on modules/apps/document-library-opener/document-library-opener-google-drive-web/src/main/java/com/liferay/document/library/opener/google/drive/web/internal/DLOpenerGoogleDriveManager.java
> +				_log.debug("The GoogleDrive file does not exist", exception);
"... GoogleDrive ..." -> "... Google Drive ..."

2022-11-25 07:42 UTC, adolfopa commented on modules/apps/document-library-opener/document-library-opener-google-drive-web/src/main/java/com/liferay/document/library/opener/google/drive/web/internal/portlet/action/EditInGoogleDocsMVCActionCommand.java
> +				SessionErrors.add(actionRequest, "googleDriveFileWasDeleted");
Can you rename the key to "googleDriveFileMissing"?

2022-11-25 07:42 UTC, adolfopa commented on modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties
> +the-google-drive-file-was-deleted=The Google Drive file was deleted during the checkout process. Will check the file back with the saved value.
What about "The Google Drive file was not found during the checkout process. The contents previous to the checkout have been restored.". Does this accurately reflect what is happening here?

2022-11-25 07:42 UTC, adolfopa commented on modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties
> +the-google-drive-file-was-deleted=The Google Drive file was deleted during the checkout process. Will check the file back with the saved value.
Or alternatively "The Google Drive file was missing ...".

2022-11-25 08:41 UTC, tototrinh commented
Hi @adolfopa,
Thanks so much for your feedback. I updated the code. Please take a look again. Thanks.

2022-12-02 04:20 UTC, tototrinh commented
Hi @adolfopa, could you please take the time to look into this and let me know if there is anything else I need to do? Thanks.

2022-12-08 03:51 UTC, tototrinh commented
Hi @adolfop, just a friendly reminder to please. This PR has been waiting for a while so can you review it at your earliest convenience? Thanks.

2022-12-13 08:30 UTC, tototrinh commented
I update the code to solve the conflict. Thanks.

2022-12-14 09:08 UTC, adolfopa commented
@tototrinh Can you send this to liferay-lima? In general, all prs should be sent there, not to our personal accounts.

2022-12-14 09:08 UTC, closed without merging